sandbox:
  target: dev
  outputs:
      dev:
        type: sqlite
        threads: 1
        database: 'database'
        schema: 'main'
        schemas_and_paths:
          main: '/duettechnical.db'
        schema_directory: 'sqlite'